name: Kryoptic

on:
  pull_request:
    paths:
      - '**.c'
      - '**.h'
      - '**.sh'
      - .github/workflows/fedora.yml
      - '**.am'
      - doc/**
      - configure.ac
  push:

permissions:
  contents: read  #  to fetch code (actions/checkout)

env:
  BASE_DEPS: |
    build-essential docbook-xsl xsltproc gengetopt help2man pcscd check
    pcsc-tools libtool make autoconf autoconf-archive automake pkg-config
    git xxd openssl valgrind socat gawk
    libglib2.0-dev libnss3-dev gnutls-bin libusb-dev libudev-dev flex
    libnss3-tools
    libpcsclite-dev libcmocka-dev libssl-dev zlib1g-dev libreadline-dev softhsm2
  KRYOPTIC: https://github.com/latchset/kryoptic.git
  KRYOPTIC_DEPS: |
    openssl-devel cargo expect pkgconf-pkg-config gnutls-utils sqlite-devel python3-six which git"

jobs:
  fedora:
    runs-on: ubuntu-22.04
    container:
      image: fedora:latest
    steps:
      - uses: actions/checkout@v4
      - run: .github/setup-fedora.sh
      - run: .github/build.sh dist
      - name: Upload test logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: fedora-test-logs
          path: |
            tests/*.log
            src/tests/unittests/*.log
      - uses: actions/cache@v4
        id: cache-build
        with:
          path: ./*
          key: ${{ runner.os }}-${{ github.sha }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opensc-build
          path:
            opensc*.tar.gz

  #######################
  ## pkcs11-tool tests ##
  #######################

  test-kryoptic:
    runs-on: ubuntu-22.04
    container:
      image: fedora:latest
    needs: [fedora]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        id: cache-build
        with:
          path: ./*
          key: ${{ runner.os }}-${{ github.sha }}
      - name: Install Dependencies
        run: |
            dnf -y install git
      - name: Get Kryoptic
        run: git clone $KRYOPTIC
      - name: Setup Fedora
        run: .github/setup-fedora.sh kryoptic
      - name: Test
        run: .github/test-kryoptic.sh
